# Generated by Django 3.0.9 on 2020-12-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_field',
            old_name='House',
            new_name='Housing_Type',
        ),
    ]
